[project]
name = "mcdeployer3000"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "docker>=7.1.0",
    "fastapi>=0.115.8",
    "httpx>=0.28.1",
    "pytest>=8.3.4",
    "uvicorn>=0.34.0",
]
